name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Project
        run: |
          # Membuat folder 'web' jika belum ada
          mkdir -p web
          # Salin semua file kecuali folder 'web' ke dalam folder 'web'
          shopt -s extglob
          cp -r !(web) web/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
